# -*- coding: utf-8 -*-
"""FIFA 2026 ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QhD30Au-Z0sYeLfs6p5G3TMB9jz9u48

Introduction

The FIFA World Cup dataset contains historical information about FIFA World Cup tournaments, including details such as year, host country, participating teams, winners, runners-up, third and fourth place teams, number of matches played, goals scored, qualified teams, attendance, and tournament statistics. The purpose of this Exploratory Data Analysis (EDA) is to understand the dataset by checking its structure, cleaning missing values and duplicates, analyzing key statistics, and visualizing trends. Through this analysis, we will identify patterns such as the most successful teams, goal-scoring trends, attendance over the years, and other insights that help better understand the history of the FIFA World Cup.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')
pd.set_option('display.max_columns', None)

"""LOAD DATASET"""

# Change the filename if needed
df = pd.read_csv('fifa_world_cup_2026_player_performance.csv')
# If using Excel:
# df = pd.read_excel('fifa_worldcup_players.xlsx')

"""WHAT ARE THE FIVE RECORDS OF THE DATASET"""

df.head()

"""HOW MANY ROWS AND COLUMNS ARE PRESENT?"""

print(df.shape)



"""WHAT ARE THE COLUMN NAMES?"""

print(df.columns.tolist())

"""WHAT IS THE AGE DISTRIBUTION OF PLAYERS?"""

plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=15, kde=True)
plt.show()

"""WHICH NATIONALITY HAS THE MOST P,LAYERS?"""

plt.figure(figsize=(10,5))
sns.countplot(y='nationality', data=df,
order=df['nationality'].value_counts().head(10).index)
plt.show()

"""WHICH POSITIONS HAVE THE MKST PLAYERS?"""

sns.countplot(x='position', data=df)
plt.show()

"""WHICH CLUB CONTRIBUTED THE MOST PLAYERS?"""

df['club_name'].value_counts().head(10).plot(kind='bar')
plt.show()

"""WHICH PLAYERS SCORED THE MOST GOALS?"""

top=df.groupby('player_name')['goals'].sum().sort_values(ascending=False).head(10)
print(top)
top.plot(kind='bar')
plt.show()

"""WHICH PLAYERS ASSIST THE MOST GOALS?"""

top=df.groupby('player_name')['assists'].sum().sort_values(ascending=False).head(10)
print(top)
top.plot(kind='bar')
plt.show()

"""WHO ARE THE TOP PLAYERS BY PERFORMANCE SCORE?"""

top=df.sort_values('performance_score',ascending=False)[['player_name','team','position','performance_score']].head(10)
print(top)

"""WHICH GOALKEEPER HAS THE HIGHEST SAVE PERCENTAGE?"""

gk=df[df['position']=='Goalkeeper'].sort_values('save_percentage',ascending=False)
print(gk[['player_name','team','save_percentage']].head(10))

"""WHICH PLAYER CREATES THE MOST CHANCES?"""

m=df[df['position']=='Midfielder'].sort_values('key_passes',ascending=False)
print(m[['player_name','team','key_passes']].head(10))

"""WHAT IS THE CONTRIBUTION OF PLAYER RATINGS?"""

sns.histplot(df['player_rating'], bins=20, kde=True)
plt.show()

"""WHICH TEAM HIGHEST AVERAGE PLAYER RATING?"""

team=df.groupby('team')['player_rating'].mean().sort_values(ascending=False)
print(team.head(10))
team.head(10).plot(kind='bar')
plt.show()

"""DOES AGE INFLUENCE PLAYER RATING?"""

sns.scatterplot(x='age',y='player_rating',data=df)
plt.show()

"""DOES MARKET VALUE INFLUENCE PLAYER RATING?"""

sns.scatterplot(x='market_value_eur',y='player_rating',data=df)
plt.show()

"""WHICH NUMERICAL FETAURES ARE CORRELATED?"""

plt.figure(figsize=(18,14))
sns.heatmap(df.select_dtypes(include='number').corr(), cmap='coolwarm')
plt.show()

"""WHICH FEATURES ARE MOST CORRELATED WITH PLAYER RATING?"""

corr=df.select_dtypes(include='number').corr()
print(corr['player_rating'].sort_values(ascending=False))

"""WHICH FORWARDS HAVE THE HIGHEST OFFENSIVE CONTRIBUTION?"""

f=df[df['position']=='Forward'].sort_values('offensive_contribution',ascending=False)
print(f[['player_name','team','offensive_contribution']].head(10))

"""WHICH PLAYER PLAYED THE MOST MINUTES?"""

top_minutes = df.groupby("player_name")["minutes_played"].sum().sort_values(ascending=False).head(10)

print(top_minutes)

top_minutes.plot(kind="bar", figsize=(10,5), title="Top 10 Players by Minutes Played")
plt.show()

"""WHICH PLAYER RECEIVED THE MOST PLAYER OF AWARDS?"""

top_pom = df.groupby("player_name")["player_of_match_awards"].sum().sort_values(ascending=False).head(10)

print(top_pom)

top_pom.plot(kind="bar")
plt.show()

"""WHICH TEAM SCORED THE MOST GOALS"""

team_goals = df.groupby("team")["goals_team"].sum().sort_values(ascending=False)

print(team_goals)

team_goals.plot(kind="bar", figsize=(10,5))
plt.show()

"""WHICH TEAM CONCEDED THE MOST GOALS?"""

team_conceded = df.groupby("team")["goals_opponent"].sum().sort_values(ascending=False)

print(team_conceded)

team_conceded.plot(kind="bar")
plt.show()

"""Which stadium hosted the most matches?"""

stadium = df["stadium"].value_counts()

print(stadium)

stadium.plot(kind="bar")
plt.show()

"""Which city hosted the most matches?"""

city = df["city"].value_counts()

print(city)

city.plot(kind="bar")
plt.show()

"""Which tournament stage had the most matches?"""

stage = df["tournament_stage"].value_counts()

print(stage)

stage.plot(kind="bar")
plt.show()

"""Which teams won the most matches?"""

wins = df[df["match_result"]=="W"]["team"].value_counts()

print(wins)

wins.plot(kind="bar")
plt.show()

""" Which teams lost the most matches?"""

losses = df[df["match_result"]=="L"]["team"].value_counts()

print(losses)

losses.plot(kind="bar")
plt.show()

"""Which players attempted the most dribbles?"""

dribble = df.groupby("player_name")["dribbles_attempted"].sum().sort_values(ascending=False).head(10)

print(dribble)

dribble.plot(kind="bar")
plt.show()

"""Which players attempted the most crosses?"""

cross = df.groupby("player_name")["crosses"].sum().sort_values(ascending=False).head(10)

print(cross)

cross.plot(kind="bar")
plt.show()

"""Which players won the most aerial duels?"""

aerial = df.groupby("player_name")["aerial_duels_won"].sum().sort_values(ascending=False).head(10)

print(aerial)

aerial.plot(kind="bar")
plt.show()

"""WHICH PLAYER COMMITTED THE MOST FOULS?"""

fouls = df.groupby("player_name")["fouls_committed"].sum().sort_values(ascending=False).head(10)

print(fouls)

fouls.plot(kind="bar")
plt.show()

""" Which players suffered the most fouls?"""

suffered = df.groupby("player_name")["fouls_suffered"].sum().sort_values(ascending=False).head(10)

print(suffered)

suffered.plot(kind="bar")
plt.show()

"""Which players received the most yellow cards?"""

yellow = df.groupby("player_name")["yellow_cards"].sum().sort_values(ascending=False).head(10)

print(yellow)

yellow.plot(kind="bar")
plt.show()

"""Which players have the highest top speed?"""

speed = df.groupby("player_name")["top_speed_kmh"].max().sort_values(ascending=False).head(10)

print(speed)

speed.plot(kind="bar")
plt.show()

"""what is the distribution of playing positions?"""

position_counts = df["position"].value_counts()

plt.figure(figsize=(8,8))

plt.pie(
    position_counts,
    labels=position_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor':'black'}
)

plt.title("Distribution of Players by Position")
plt.axis('equal')
plt.show()

"""What is the distribution of players based on their preferred foot?"""

foot_counts = df["preferred_foot"].value_counts()

plt.figure(figsize=(7,7))

plt.pie(
    foot_counts,
    labels=foot_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor':'black'}
)

plt.title("Distribution of Players by Preferred Foot")
plt.axis('equal')
plt.show()

"""What is the distribution of match results?"""

result_counts = df["match_result"].value_counts()

plt.figure(figsize=(7,7))

plt.pie(
    result_counts,
    labels=result_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor':'black'}
)

plt.title("Distribution of Match Results")
plt.axis('equal')
plt.show()